Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    #
    # Run Ansible from the Vagrant Host
    #
    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.name = "server_test"   
    end
    config.vm.network "private_network", ip: "10.29.111.110"
  
  end
  